project:
  type: website

website:
  title: "OpticalBlochEquations.jl"
  sidebar:
    style: "docked"
    search: false
    alignment: "center"
    contents:
      - section: "Examples"
        alignment: "center"
        contents:
          - text: "Blue-detuned MOT for CaOH"
            file: "ipynb_sources/Blue-detuned MOT (CaOH).ipynb"

format:
  html:
    page-layout: full
    # theme: cosmo
    # css: styles.css
    # toc: true

freeze: auto