project:
  type: website

website:
  title: "OpticalBlochEquations.jl"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - text: "Example 1"
        file: "ipynb_sources/Blue-detuned MOT (CaOH).ipynb"
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

freeze: auto